-- Artisanal repos: 100+ stars, active in last 6 months, zero AI involvement
-- Run against: clickhouse client --host play.clickhouse.com --user play --secure

WITH
  ai_actors AS (
    -- Anthropic
    SELECT 'claude[bot]' AS actor UNION ALL
    SELECT 'anthropic[bot]' UNION ALL
    -- OpenAI / Codex
    SELECT 'chatgpt-codex-connector[bot]' UNION ALL
    SELECT 'copilot' UNION ALL
    SELECT 'github-copilot[bot]' UNION ALL
    SELECT 'copilot-workspace[bot]' UNION ALL
    -- Google
    SELECT 'google-labs-jules[bot]' UNION ALL
    SELECT 'gemini-code-assist[bot]' UNION ALL
    -- Cognition (Devin)
    SELECT 'devin-ai-integration[bot]' UNION ALL
    SELECT 'devin[bot]' UNION ALL
    -- Cursor
    SELECT 'cursor[bot]' UNION ALL
    -- Amazon
    SELECT 'amazon-q-developer[bot]' UNION ALL
    -- Lovable
    SELECT 'lovable-dev[bot]' UNION ALL
    -- Code review bots
    SELECT 'coderabbitai[bot]' UNION ALL
    SELECT 'sourcery-ai[bot]' UNION ALL
    SELECT 'qodo-merge-pro[bot]' UNION ALL
    SELECT 'codeflash-ai[bot]' UNION ALL
    -- Sweep
    SELECT 'sweep-ai[bot]' UNION ALL
    SELECT 'sweep[bot]' UNION ALL
    -- Other AI coding bots
    SELECT 'codegen-bot' UNION ALL
    SELECT 'aider-bot' UNION ALL
    SELECT 'gpt-pilot[bot]' UNION ALL
    SELECT 'tabnine[bot]' UNION ALL
    SELECT 'cody[bot]'
  ),
  ai_repos AS (
    SELECT DISTINCT repo_name
    FROM github_events
    WHERE created_at > now() - INTERVAL 12 MONTH
      AND (
        -- AI actor: pushes, PRs, or comments
        (actor_login IN (SELECT actor FROM ai_actors)
         AND event_type IN ('PushEvent', 'PullRequestEvent', 'IssueCommentEvent', 'PullRequestReviewCommentEvent'))
        -- AI commit message patterns
        OR (event_type = 'PushEvent' AND (
          body ILIKE '%noreply@anthropic.com%'
          OR body ILIKE '%Co-authored-by:%Claude%'
          OR body ILIKE '%Co-authored-by:%Copilot%'
          OR body ILIKE '%Co-authored-by:%GPT%'
          OR body ILIKE '%Co-authored-by:%Gemini%'
          OR body ILIKE '%Generated by Claude%'
          OR body ILIKE '%Generated by Copilot%'
          OR body ILIKE '%Generated by Codex%'
          OR body ILIKE '%[cursor]%'
          OR body ILIKE '%[aider]%'
          OR body ILIKE '%[lovable]%'
        ))
      )
  ),
  starred AS (
    SELECT repo_name, count() AS stars
    FROM github_events
    WHERE event_type = 'WatchEvent'
    GROUP BY repo_name
    HAVING stars >= 100
  ),
  active AS (
    SELECT repo_name, max(created_at) AS last_activity, count() AS commits
    FROM github_events
    WHERE event_type = 'PushEvent'
      AND created_at > now() - INTERVAL 6 MONTH
    GROUP BY repo_name
  )
SELECT
  s.repo_name AS repo,
  s.stars,
  a.commits,
  formatDateTime(a.last_activity, '%Y-%m-%d') AS last_active
FROM starred s
JOIN active a ON s.repo_name = a.repo_name
WHERE s.repo_name NOT IN (SELECT repo_name FROM ai_repos)
ORDER BY s.stars DESC
LIMIT 200
